spring:
   datasource:
      driverClassName: org.h2.Driver
      password: ''
      url: jdbc:h2:mem:rota2010
      username: sa
      
   h2:
      console:
         enabled: true
         path: /h2-console
         
   jpa:
      database-plataform: org.hibernate.dialect.H2Dialect
      show-sql: true
      hibernate:
         format_sql: true
         ddl-auto: update
                  
   rabbitmq:
      request:
         host: localhost
         port: 5672
         username: guest
         password: guest
         exchange:
            producer: ex.producer.rota2030
         routing-key:
            producer: rk.producer.rota2030
         deadletter:
            producer: dl.producer.rota203000
            
rota2030:
   jwt:
      expiration: 86400000
      secret: rm$!@N=Ke!~p8VTA2ZRoizxh4r556hv[]]K~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa9eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/