INSERT INTO GRUPO(GRUPO_ID,GRUPO_DESCRICAO) VALUES(1,'Grupo A');
INSERT INTO GRUPO(GRUPO_ID,GRUPO_DESCRICAO) VALUES(2,'Grupo B');
INSERT INTO GRUPO(GRUPO_ID,GRUPO_DESCRICAO) VALUES(3,'Grupo C');

INSERT INTO TIPO(TIPO_ID,TIPO_DESCRICAO) VALUES(1,'Automovel');
INSERT INTO TIPO(TIPO_ID,TIPO_DESCRICAO) VALUES(2,'Caminhonete');
INSERT INTO TIPO(TIPO_ID,TIPO_DESCRICAO) VALUES(3,'Utilitario');

INSERT INTO ITEM_DE_SEGURANCA(ITEM_DE_SEGURANCA_DESCRICAO,
							  ITEM_DE_SEGURANCA_NORMA_CONTRAM,
							  ITEM_DE_SEGURANCA_OBRIGATORIO,
							  GRUPO_ID,
							  TIPO_ID) VALUES('Item W', 'Norma W', true, 1, 1);

INSERT INTO ITEM_DE_SEGURANCA(ITEM_DE_SEGURANCA_DESCRICAO,
							  ITEM_DE_SEGURANCA_NORMA_CONTRAM,
							  ITEM_DE_SEGURANCA_OBRIGATORIO,
							  GRUPO_ID,
							  TIPO_ID) VALUES('Item X', 'Norma X', true, 1, 1);

INSERT INTO ITEM_DE_SEGURANCA(ITEM_DE_SEGURANCA_DESCRICAO,
							  ITEM_DE_SEGURANCA_NORMA_CONTRAM,
							  ITEM_DE_SEGURANCA_OBRIGATORIO,
							  GRUPO_ID,
							  TIPO_ID) VALUES('Item Y', 'Norma Y', false, 2, 2);
							  
INSERT INTO ITEM_DE_SEGURANCA(ITEM_DE_SEGURANCA_DESCRICAO,
							  ITEM_DE_SEGURANCA_NORMA_CONTRAM,
							  ITEM_DE_SEGURANCA_OBRIGATORIO,
							  GRUPO_ID,
							  TIPO_ID) VALUES('Item Z', 'Norma Z', 	true, 3, 3);
							  
INSERT INTO PERFIL_ACESSO_USUARIO(PERFIL_DESCRICAO) VALUES('Master');
INSERT INTO PERFIL_ACESSO_USUARIO(PERFIL_DESCRICAO) VALUES('Admin');
INSERT INTO PERFIL_ACESSO_USUARIO(PERFIL_DESCRICAO) VALUES('User');

INSERT INTO USUARIO(USUARIO_LOGIN,
                    USUARIO_EMAIL,
                    USUARIO_DATA_ULTIMO_ACESSO) VALUES('User', 'user@test.com', {ts '2021-04-12 18:47:52.69'} );
                    
INSERT INTO USUARIO(USUARIO_LOGIN,
                    USUARIO_EMAIL,
                    USUARIO_DATA_ULTIMO_ACESSO) VALUES('Admin', 'admin@test.com', {ts '2020-11-12 18:47:52.69'} );    
                    
INSERT INTO USUARIO_PERFIL(USUARIO_ID, PERFIL_ID) VALUES(1,3);
INSERT INTO USUARIO_PERFIL(USUARIO_ID, PERFIL_ID) VALUES(2,2);

 
							  
